dragonfly-science/dragonfly-website

content/work/delphi-case-study.md

Delphi case study

---

content/news/2018-05-14-miles-thompson/content.md

1. Not quite right to say my day job for four years was chief technical officer
.. changed it to say my "day job for five years was chief technology officer "
2. Not factually correct to say "Although he’d studied neural networks at university, he hadn’t ever used them."
..changed it to "Although he’d studied neural networks at university,  he had only used them in a research context prior to that time. 
3. Changed our hardware to just 'hardware'. It wasn't a question of 'our' hardware but computers generally. ,

Great work.. but need to correct a couple of small things

---

content/people/calcott-brett/content.md
content/people/damodaran-dayanitha/content.md
content/people/menzies-ignatius/content.md
content/people/wilkinson-nikki/content.md
content/people/winter-simon/content.md
content/people/zuijderwijk-pep/content.md

new profiles

---

content/work/NEFD-case-study/content.md

NEFD case study text updates

---

content/index.md
content/landing-pages/what-we-do/content.md
content/landing-pages/who-we-are/content.md
content/landing-pages/work/content.md
content/news.md

Top page edits

---

content/templates/_footer.html
front-end/src/js/carousel.ts
front-end/src/stylesheets/layout/main-footer.src.css
front-end/src/stylesheets/layout/modal.src.css

updates to carousel request animation frame.

fix(footer): mobile footer resolved

---

content/testimonials/Antipodean-albatross-testimonial/content.md
content/work/Antipodean-albatross-case-study/content.md

Added content in work and testimonials. Pep has the images to add but can't get to it till later in the week

Antipodean albatross case study

---

content/testimonials/warp-strike-testimonial/content.md

Replacing with correct test (had been copied from koala case study). @simonwinter See if this master to master PR works for you!

Warp strike testimonial

---

content/news/2021-09-20-fabian-doweler-treelines/content.md
content/news/2021-10-14-emma-crawford-kakapo/content.md
content/people/crawford-emma/content.md
content/people/neubauer-philipp/content.md

A few small tweaks and updated Emma profile

Corrections and additions to news stories and profiles

---

content/people/crawford-emma/content.md

Emma's profile

---

content/work/Antipodean-albatross-case-study/content.md

Replacing missing text  

---

content/people/kim-kyuhan/content.md
content/people/selvaraj-sadhvi/content.md
content/people/thompson-finlay/content.md
content/people/zuijderwijk-pep/content.md
content/work/Antipodean-albatross-case-study/content.md
content/work/INZ-case-study/content.md
content/work/NEFD-case-study/content.md
content/work/TMP-case-study/content.md
content/work/delphi-case-study/content.md
content/work/navigating-complexity/content.md
content/work/nms-case-study/content.md
content/work/protected-species-data/content.md
content/work/rec-fishing-bycatch/content.md
content/work/vibrant-planet/content.md
content/work/warp-strike/content.md

Added sort orders to case studies and removed phonetics from profiles. (Ed happy for me to make these changes )

Edits to people and case study pages

---

content/people/kim-kyuhan/content.md
content/people/selvaraj-sadhvi/content.md
content/people/thompson-finlay/content.md
content/people/zuijderwijk-pep/content.md
content/work/Antipodean-albatross-case-study/content.md
content/work/INZ-case-study/content.md
content/work/NEFD-case-study/content.md
content/work/TMP-case-study/content.md
content/work/delphi-case-study/content.md
content/work/navigating-complexity/content.md
content/work/nms-case-study/content.md
content/work/protected-species-data/content.md
content/work/rec-fishing-bycatch/content.md
content/work/vibrant-planet/content.md
content/work/warp-strike/content.md

Change display order of case studies on work page.

Updates to case study ordering

---

content/news/2022-03-18-muxd/content.md
content/news/2022-05-20-amelia-cordwell/content.md

Moved the full stops so captions appear

Photo caption fixes

---

content/index.md

Added 2 new testimonials (including VP) to home page animation

New testimonials

---

content/news/2022-07-04-gold-awards/content.md
content/people/zwart-henry/content.md

Removing a sentence from Henry Z profile. Added link and trying to get rid of the bold type on the the bottom of the Gold Awards

Tidy ups on recent content

---

content/news/2022-07-07-nuclear-winter/content.md
content/vacancies.md
content/vacancies/project-managers-2022-07-12/content.md

Adding PM jobs and fixing typo

---

content/index.md

This is for the scrolling quotes on the home page

Added Elias testimonial

---

content/people/abraham-edward/content.md
content/people/berkenbusch-katrin/content.md
content/people/neubauer-philipp/content.md
content/people/thompson-finlay/content.md
content/publications/berkenbusch_intertidal_2021.md
content/publications/berkenbusch_intertidal_2023.md

update publication page

---

content/news/2024-08-27-avian-flu/content.md
content/news/2024-08-28-forest-mapping/content.md
content/work/avian-flu-case-study/content.md

These updates include Brett's revision to the avian flu story under Projects and under News, and my edits. Building under the UAT.

updates to the avian flu stories (under projects and under news)

---

content/work/thematic-analysis-case-study/content.md

include emma in project team otbnz
